[package]
name = "rust_cube"
version = "0.1.0"
edition = "2018"

# Dependencies
[dependencies]
#warp = "0.3"
#tokio = { version = "1", features = ["full"] }
#futures-util = "0.3"
#bytes = "1"
#mime_guess = "2.0"

